// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SaaS.Infrastructure.Data;

#nullable disable

namespace SaaS.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260410230329_AddSocialMediaTable")]
    partial class AddSocialMediaTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SaaS.Domain.Entities.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AdminUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "905467BFFB1C7089C8AD917EDF98DAAD87191171EFDC6F60229794C182CA48F6",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("SaaS.Domain.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessId")
                        .HasColumnType("integer");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("SaaS.Domain.Entities.BlogPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BlogPosts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Uzun zamandır üzerinde çalıştığım yeni nesil tasarım altyapım nihayet tamamlandı. İşletmeler kendilerine özel sistemleri kusursuz bir performansla kullanabiliyorlar.",
                            CreatedAt = new DateTime(2026, 4, 8, 23, 3, 28, 806, DateTimeKind.Utc).AddTicks(3041),
                            Summary = "Tasarım süreçlerimi ve teknolojiyi nasıl harmanladığım hakkında ufak bir günlük.",
                            Title = "Yeni Portfolyo Yayında"
                        });
                });

            modelBuilder.Entity("SaaS.Domain.Entities.Business", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subdomain")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Businesses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Vogue Kuafor",
                            Subdomain = "kuafor",
                            Type = "Kuafor"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Espresso Kafe",
                            Subdomain = "kafe",
                            Type = "Kafe"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Tech Store",
                            Subdomain = "ecommerce",
                            Type = "Ecommerce"
                        });
                });

            modelBuilder.Entity("SaaS.Domain.Entities.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("SaaS.Domain.Entities.DemoProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DemoProjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Online randevu sistemi ve dijital asistan.",
                            ImageUrl = "https://images.unsplash.com/photo-1562322140-8baeececf3df?q=80&w=800",
                            Link = "http://kuafor.localhost",
                            Title = "Kuaför & Güzellik"
                        },
                        new
                        {
                            Id = 2,
                            Description = "QR destekli masa siparişi ve dijital menü.",
                            ImageUrl = "https://images.unsplash.com/photo-1554118811-1e0d58224f24?q=80&w=600",
                            Link = "http://kafe.localhost",
                            Title = "Kafe & Restoran"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Modern sepet ve gelişmiş ödeme sistemleri.",
                            ImageUrl = "https://images.unsplash.com/photo-1472851294608-062f824d29cc?q=80&w=600",
                            Link = "http://ecommerce.localhost",
                            Title = "E-Ticaret Altyapısı"
                        },
                        new
                        {
                            Id = 4,
                            Description = "İşletmenizi dijitalleştiren akıllı müşteri yönetim ve otomasyon paneli.",
                            ImageUrl = "https://images.unsplash.com/photo-1551288049-bbdac8a28a1e?q=80&w=800",
                            Link = "#",
                            Title = "CRM Otomasyonv1.1"
                        });
                });

            modelBuilder.Entity("SaaS.Domain.Entities.PortfolioService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PortfolioServices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Arama motorlarında görünürlüğünüzü artırın ve daha fazla müşteriye ulaşın.",
                            Icon = "search_insights",
                            Title = "SEO HİZMETİ"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Modern, hızlı ve dönüşüm odaklı web siteleri tasarlıyoruz.",
                            Icon = "web",
                            Title = "WEB SİTESİ HİZMETİ"
                        },
                        new
                        {
                            Id = 3,
                            Description = "iOS ve Android platformları için yüksek performanslı mobil çözümler.",
                            Icon = "smartphone",
                            Title = "MOBİL UYGULAMA HİZMETİ"
                        },
                        new
                        {
                            Id = 4,
                            Description = "İş süreçlerinizi optimize edin ve verimliliğinizi artırın.",
                            Icon = "robot",
                            Title = "OTOMASYON HİZMETİ"
                        });
                });

            modelBuilder.Entity("SaaS.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BusinessId = 2,
                            Description = "Creamy latte",
                            ImageUrl = "https://images.unsplash.com/photo-1541167760496-1628856ab772?q=80&w=1037&auto=format&fit=crop",
                            Name = "Latte",
                            Price = 80m
                        },
                        new
                        {
                            Id = 2,
                            BusinessId = 2,
                            Description = "Chocolate coffee",
                            ImageUrl = "https://images.unsplash.com/photo-1578314675249-a6910f80cc4e?q=80&w=1014&auto=format&fit=crop",
                            Name = "Mocha",
                            Price = 95m
                        },
                        new
                        {
                            Id = 3,
                            BusinessId = 3,
                            Description = "RGB Keyboard",
                            ImageUrl = "https://images.unsplash.com/photo-1595225476474-87563907a212?q=80&w=1171&auto=format&fit=crop",
                            Name = "Mechanical Keyboard",
                            Price = 1500m
                        });
                });

            modelBuilder.Entity("SaaS.Domain.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessId")
                        .HasColumnType("integer");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BusinessId = 1,
                            DurationMinutes = 30,
                            Name = "Saç Kesimi",
                            Price = 250m
                        },
                        new
                        {
                            Id = 2,
                            BusinessId = 1,
                            DurationMinutes = 20,
                            Name = "Fön",
                            Price = 100m
                        });
                });

            modelBuilder.Entity("SaaS.Domain.Entities.SiteContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("SectionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SiteContents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Amacım, markanızı dijital dünyada en şık ve güçlü şekilde temsil etmektir. Yalnızca iyi görünmekle kalmayan, aynı zamanda müşterilerinize pürüzsüz bir deneyim sunan projeler üretiyorum.",
                            SectionName = "AboutMe",
                            Title = "Estetik ve performans, ayrıntılarda gizlidir."
                        },
                        new
                        {
                            Id = 2,
                            Content = "905555555555",
                            SectionName = "ContactInfo",
                            Title = "iletisim@volkanb.com"
                        },
                        new
                        {
                            Id = 3,
                            Content = "https://github.com",
                            ImageUrl = "https://twitter.com",
                            SectionName = "SocialLinks",
                            Title = "https://linkedin.com"
                        });
                });

            modelBuilder.Entity("SaaS.Domain.Entities.SocialMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BrandColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IconSvg")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("PlatformName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SocialMedias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandColor = "#FF0000",
                            IconSvg = "<svg viewBox=\"0 0 24 24\" fill=\"currentColor\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M23.498 6.186a3.016 3.016 0 0 0-2.122-2.136C19.505 3.545 12 3.545 12 3.545s-7.505 0-9.377.505A3.017 3.017 0 0 0 .502 6.186C0 8.07 0 12 0 12s0 3.93.502 5.814a3.016 3.016 0 0 0 2.122 2.136c1.871.505 9.376.505 9.376.505s7.505 0 9.377-.505a3.015 3.015 0 0 0 2.122-2.136C24 15.93 24 12 24 12s0-3.93-.502-5.814zM9.545 15.568V8.432L15.818 12l-6.273 3.568z\"/></svg>",
                            IsActive = true,
                            Order = 1,
                            PlatformName = "YouTube",
                            Url = "https://youtube.com"
                        },
                        new
                        {
                            Id = 2,
                            BrandColor = "#53fc18",
                            IconSvg = "<svg viewBox=\"0 0 24 24\" fill=\"currentColor\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M18.8 3.5h-4.3v4.3h-2.2V3.5h-4.3v17h4.3v-4.3h2.2v4.3h4.3v-17zM14.5 12.1h-2.2V9.9h2.2v2.2z\"/></svg>",
                            IsActive = true,
                            Order = 2,
                            PlatformName = "Kick",
                            Url = "https://kick.com"
                        },
                        new
                        {
                            Id = 3,
                            BrandColor = "#E4405F",
                            IconSvg = "<svg viewBox=\"0 0 24 24\" fill=\"currentColor\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M12 2.163c3.204 0 3.584.012 4.85.07 3.252.148 4.771 1.691 4.919 4.919.058 1.265.069 1.645.069 4.849s-.011 3.585-.069 4.85c-.149 3.225-1.664 4.771-4.919 4.919-1.266.058-1.644.07-4.85.07s-3.584-.012-4.849-.07c-3.26-.149-4.771-1.699-4.919-4.92-.058-1.265-.07-1.644-.07-4.849s.012-3.584.07-4.849c.149-3.227 1.664-4.771 4.919-4.919 1.266-.057 1.645-.069 4.849-.069zM12 0C8.741 0 8.333.014 7.053.072 2.695.272.273 2.69.073 7.052.014 8.333 0 8.741 0 12c0 3.259.014 3.668.072 4.948.2 4.358 2.618 6.78 6.98 6.98 1.281.058 1.689.072 4.948.072 3.259 0 3.668-.014 4.948-.072 4.354-.2 6.782-2.618 6.979-6.98.059-1.28.073-1.689.073-4.948 0-3.259-.014-3.667-.072-4.947-.196-4.354-2.617-6.78-6.979-6.98C15.668.014 15.259 0 12 0zm0 5.838a6.162 6.162 0 1 0 0 12.324 6.162 6.162 0 0 0 0-12.324zM12 16a4.162 4.162 0 1 1 0-8.324 4.162 4.162 0 0 1 0 8.324zm6.406-11.845a1.44 1.44 0 1 0 0 2.881 1.44 1.44 0 0 0 0-2.881z\"/></svg>",
                            IsActive = true,
                            Order = 3,
                            PlatformName = "Instagram",
                            Url = "https://instagram.com"
                        },
                        new
                        {
                            Id = 4,
                            BrandColor = "#0A66C2",
                            IconSvg = "<svg viewBox=\"0 0 24 24\" fill=\"currentColor\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.225 0z\"/></svg>",
                            IsActive = true,
                            Order = 4,
                            PlatformName = "LinkedIn",
                            Url = "https://linkedin.com"
                        },
                        new
                        {
                            Id = 5,
                            BrandColor = "#25d366",
                            IconSvg = "<svg viewBox=\"0 0 24 24\" fill=\"currentColor\" xmlns=\"http://www.w3.org/2000/svg\"><path d=\"M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413z\"/></svg>",
                            IsActive = true,
                            Order = 5,
                            PlatformName = "WhatsApp",
                            Url = "https://wa.me/905000000000"
                        });
                });

            modelBuilder.Entity("SaaS.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("SaaS.Domain.Entities.Business", "Business")
                        .WithMany("Appointments")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("SaaS.Domain.Entities.Product", b =>
                {
                    b.HasOne("SaaS.Domain.Entities.Business", "Business")
                        .WithMany("Products")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("SaaS.Domain.Entities.Service", b =>
                {
                    b.HasOne("SaaS.Domain.Entities.Business", "Business")
                        .WithMany("Services")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("SaaS.Domain.Entities.Business", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Products");

                    b.Navigation("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
