// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SaaS.Infrastructure.Data;

#nullable disable

namespace SaaS.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260408031958_AddDemoProjectsAndSettings")]
    partial class AddDemoProjectsAndSettings
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SaaS.Domain.Entities.AdminUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AdminUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = "905467BFFB1C7089C8AD917EDF98DAAD87191171EFDC6F60229794C182CA48F6",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("SaaS.Domain.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessId")
                        .HasColumnType("integer");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("SaaS.Domain.Entities.BlogPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BlogPosts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Uzun zamandır üzerinde çalıştığım yeni nesil tasarım altyapım nihayet tamamlandı. İşletmeler kendilerine özel sistemleri kusursuz bir performansla kullanabiliyorlar.",
                            CreatedAt = new DateTime(2026, 4, 6, 3, 19, 57, 489, DateTimeKind.Utc).AddTicks(6329),
                            Summary = "Tasarım süreçlerimi ve teknolojiyi nasıl harmanladığım hakkında ufak bir günlük.",
                            Title = "Yeni Portfolyo Yayında"
                        });
                });

            modelBuilder.Entity("SaaS.Domain.Entities.Business", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subdomain")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Businesses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Vogue Kuafor",
                            Subdomain = "kuafor",
                            Type = "Kuafor"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Espresso Kafe",
                            Subdomain = "kafe",
                            Type = "Kafe"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Tech Store",
                            Subdomain = "ecommerce",
                            Type = "Ecommerce"
                        });
                });

            modelBuilder.Entity("SaaS.Domain.Entities.DemoProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DemoProjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Online randevu sistemi ve dijital asistan.",
                            ImageUrl = "https://images.unsplash.com/photo-1562322140-8baeececf3df?q=80&w=800",
                            Link = "http://kuafor.localhost",
                            Title = "Kuaför & Güzellik"
                        },
                        new
                        {
                            Id = 2,
                            Description = "QR destekli masa siparişi ve dijital menü.",
                            ImageUrl = "https://images.unsplash.com/photo-1554118811-1e0d58224f24?q=80&w=600",
                            Link = "http://kafe.localhost",
                            Title = "Kafe & Restoran"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Modern sepet ve gelişmiş ödeme sistemleri.",
                            ImageUrl = "https://images.unsplash.com/photo-1472851294608-062f824d29cc?q=80&w=600",
                            Link = "http://ecommerce.localhost",
                            Title = "E-Ticaret Altyapısı"
                        });
                });

            modelBuilder.Entity("SaaS.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BusinessId = 2,
                            Description = "Creamy latte",
                            ImageUrl = "https://images.unsplash.com/photo-1541167760496-1628856ab772?q=80&w=1037&auto=format&fit=crop",
                            Name = "Latte",
                            Price = 80m
                        },
                        new
                        {
                            Id = 2,
                            BusinessId = 2,
                            Description = "Chocolate coffee",
                            ImageUrl = "https://images.unsplash.com/photo-1578314675249-a6910f80cc4e?q=80&w=1014&auto=format&fit=crop",
                            Name = "Mocha",
                            Price = 95m
                        },
                        new
                        {
                            Id = 3,
                            BusinessId = 3,
                            Description = "RGB Keyboard",
                            ImageUrl = "https://images.unsplash.com/photo-1595225476474-87563907a212?q=80&w=1171&auto=format&fit=crop",
                            Name = "Mechanical Keyboard",
                            Price = 1500m
                        });
                });

            modelBuilder.Entity("SaaS.Domain.Entities.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BusinessId")
                        .HasColumnType("integer");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BusinessId = 1,
                            DurationMinutes = 30,
                            Name = "Saç Kesimi",
                            Price = 250m
                        },
                        new
                        {
                            Id = 2,
                            BusinessId = 1,
                            DurationMinutes = 20,
                            Name = "Fön",
                            Price = 100m
                        });
                });

            modelBuilder.Entity("SaaS.Domain.Entities.SiteContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("SectionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SiteContents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Amacım, markanızı dijital dünyada en şık ve güçlü şekilde temsil etmektir. Yalnızca iyi görünmekle kalmayan, aynı zamanda müşterilerinize pürüzsüz bir deneyim sunan projeler üretiyorum.",
                            SectionName = "AboutMe",
                            Title = "Estetik ve performans, ayrıntılarda gizlidir."
                        },
                        new
                        {
                            Id = 2,
                            Content = "905555555555",
                            SectionName = "ContactInfo",
                            Title = "iletisim@portfolyopro.com"
                        },
                        new
                        {
                            Id = 3,
                            Content = "https://github.com",
                            ImageUrl = "https://twitter.com",
                            SectionName = "SocialLinks",
                            Title = "https://linkedin.com"
                        });
                });

            modelBuilder.Entity("SaaS.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("SaaS.Domain.Entities.Business", "Business")
                        .WithMany("Appointments")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("SaaS.Domain.Entities.Product", b =>
                {
                    b.HasOne("SaaS.Domain.Entities.Business", "Business")
                        .WithMany("Products")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("SaaS.Domain.Entities.Service", b =>
                {
                    b.HasOne("SaaS.Domain.Entities.Business", "Business")
                        .WithMany("Services")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");
                });

            modelBuilder.Entity("SaaS.Domain.Entities.Business", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Products");

                    b.Navigation("Services");
                });
#pragma warning restore 612, 618
        }
    }
}
